# Copy file to planeur.net FTP server

name: 1.3 - Create XCSoar _details.txt + version + zip

# Controls when the workflow will run
on:
  # Triggers the workflow After the version has been added
  workflow_run:
    workflows: ["1.2 - Create .kmz"]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# see: https://github.com/marketplace/actions/ftp-deployment
jobs:
  convert-to-xcsoar:
    if: github.ref == 'refs/heads/main' && github.repository == 'planeur-net/outlanding'
    name: create xcsoar details
    runs-on: ubuntu-latest
    steps:

    - name: 🚚 Get latest code for outlanding
      uses: actions/checkout@v3
      with:
        path: ./outlanding

    - name: 🚚 Get latest code for cup2xcsoar
      uses: actions/checkout@v3
      with:
        repository: llauner/cup2xcsoar
        token: ${{ secrets.ACCESS_TOKEN_CUP2KMZ }}
        path: ./cup2xcsoar
        ref: master

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - name: Install dependencies
      run: | 
        cd ./cup2xcsoar
    
    - name: ⚙️ Create _details.txt
      id: create_details
      run: |
        echo "### Create guide_aires_securite_details.txt"
        cd ./cup2xcsoar
        node ./cupToXCSoar.js ../outlanding/guide_aires_securite.cup

        echo "### Copy _details to outlanding repo location"
        cp ./guide_aires_securite_details.txt ../outlanding/


    - name: Set version
      id: set_version
      run: |
        # Get information
        cd ./outlanding
        git log --pretty="%h %cI" -n1 -- guide_aires_securite.cup
        versionInfo=$(git log --pretty="%h %cI" -n1 -- guide_aires_securite.cup)
        # Remove first line if applicable
        sed -i "$((grep -nm1 \"[version] ./guide_aires_securite_details.txt || echo 1000000000:) | cut -f 1 -d:) d" ./guide_aires_securite_details.txt
        # Add version information
        sed -i "2i $versionInfo" ./guide_aires_securite_details.txt



    - name: Create ZIP for XCSoar folder
      id: create-zip
      run: |
        echo "### Create ZIP to be copied to XCSoar folder"
        cd ./outlanding
        zip guide_aires_securite.xcsoar.zip guide_aires_securite.cup guide_aires_securite_details.txt Pics/     


    - name: ⚙️ Push to repo
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        repository: ./outlanding
        commit_message: Test Ludovic

